export const awardsArray = [
	{ text: "awards.corea", link: "http://www.revistacomunicacion.org/pdf/n16/Articulos/A3_GarciaRosales_Analisis_semiotica_profunda_propaganda_Corea.pdf", type: "scientific"},
	{ text: "awards.corea", link: "http://www.revistacomunicacion.org/pdf/n14/Articulos/A5_Salazar-Garcia-Rosales-Analisis-de-los-elementos-estetico-expresivos-en-la-propaganda-de-Corea-del-Sur-y-Corea-del-Norte.pdf", type: "scientific" },
	{ text: "awards.interview", link: "https://www.youtube.com/watch?v=ljT-Zwobxos&feature=emb_title&ab_channel=ITgals", type: "others" },
	{ text: "awards.articleOne", link: "https://medium.com/@marasalazar/developers-nightmare-web-accessibility-52b9a6890403", type: "article" },
	{ text: "awards.articleTwo", link: "https://medium.com/@marasalazar/why-icomoon-why-15c2d78ec96e", type: "article"  },
	{ text: "awards.articleThree", link: "https://marasalazar.medium.com/how-to-structure-css-in-vue-like-a-pro-5475749cf5ea", type: "article"  },
	{ text: "awards.articleFive", link: "https://marasalazar.medium.com/c%C3%B3mo-dar-soporte-a-ie-y-no-morir-en-el-intento-7049dcbbf43f", type: "article"  },
	{ text: "awards.articleFour", link: "https://marasalazar.medium.com/to-angular-material-or-not-to-angular-material-940a616ac22d", type: "article"  },
	{ text: "awards.articleSix", link: "https://blog.enthec.com/the-importance-of-maintaining-the-health-of-your-dns/", type: "article"  },
	{ text: "awards.articleSiven", link: "https://blog.enthec.com/discover-how-to-protect-your-company-from-web-exposition-with-kartos/", type: "article"  },
	{ text: "awards.articleEight", link: "https://blog.enthec.com/why-are-data-leaks-dangerous-and-how-to-prevent-them/", type: "article"  },
	{ text: "awards.articleNine", link: "https://blog.enthec.com/leaked-credentials-the-importance-of-employees-awareness/", type: "article"  },
	{ text: "awards.articleTen", link: "https://blog.enthec.com/5-types-of-phishing-and-how-to-protect-from-them/", type: "article"  },
	{ text: "awards.articleEleven", link: "https://blog.enthec.com/10-cybersecurity-tips-for-remote-workers/", type: "article"  },
	{ text: "awards.articleTwelve", link: "https://blog.enthec.com/9-tips-to-protect-yourself-from-identity-theft//", type: "article"  },
	{ text: "awards.videogame", link: "https://xcjgames.itch.io/treeventure", type: "others" },
	{ text: "awards.videogameTwo", link: "https://xcjgames.itch.io/damng-la-balada-del-capitan", type: "others" },
];